/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by scripts/generate-build-info.js at build time.
 * This file is gitignored and regenerated on every build.
 */

export interface FrontendBuildInfo {
  /** Build version from environment file (fallback: package.json) */
  version: string;
  /** UTC ISO timestamp of when the build was created */
  buildDateUtc: string;
  /** Short git commit hash (7 chars) */
  gitCommitShort: string;
  /** Full git commit hash */
  gitCommitFull: string;
  /** Output of git describe --tags --always --dirty */
  gitDescribe: string;
  /** Exact tag at HEAD, if any (null otherwise) */
  gitTagExact: string | null;
  /** Git branch name (from CI env or git) */
  branch: string;
  /** CI build number, if running in CI (null otherwise) */
  ciBuildNumber: string | null;
}

export const FRONTEND_BUILD_INFO: FrontendBuildInfo = {
  version: "2.3.4",
  buildDateUtc: "2026-02-19T00:06:38.026Z",
  gitCommitShort: "b0e1b8b4",
  gitCommitFull: "b0e1b8b4a0acb1aedb34e821928b40e6c84bc87b",
  gitDescribe: "iaro_upgrade_ng20_pre_sync_2026-02-09-52-gb0e1b8b4",
  gitTagExact: null,
  branch: "iaro_build_version",
  ciBuildNumber: null
};
