export const formSections: { [substanceType: string]: Array<string> } = {
    chemical: [
        'substance-form-definition',
        'substance-form-names',
        'substance-form-structure',
        'substance-form-moieties',
        'substance-form-codes',
        'substance-form-relationships',
        'substance-form-notes',
        'substance-form-properties',
        'substance-form-references'
    ],
  protein: [
    'substance-form-definition',
    'substance-form-names',
    'substance-form-protein-details',
    'substance-form-subunits',
    'substance-form-other-links',
    'substance-form-disulfide-links',
    'substance-form-glycosylation',
    'substance-form-agent-modifications',
    'substance-form-structural-modifications',
    'substance-form-physical-modifications',
    'substance-form-codes',
    'substance-form-relationships',
    'substance-form-notes',
    'substance-form-properties',
    'substance-form-references',
  ],
  nucleicAcid: [
    'substance-form-definition',
    'nucleic-acid-details-form',
    'substance-form-subunits',
    'substance-form-links',
    'substance-form-sugars',
    'substance-form-names',
    'substance-form-codes',
    'substance-form-relationships',
    'substance-form-properties',
    'substance-form-notes',
    'substance-form-references',
    'substance-form-physical-modifications',
    'substance-form-agent-modifications',
    'substance-form-structural-modifications',
  ],
  mixture: [
    'substance-form-definition',
    'substance-form-names',
    'substance-form-mixture-details',
    'substance-form-mixture-components',
    'substance-form-agent-modifications',
    'substance-form-structural-modifications',
    'substance-form-physical-modifications',
    'substance-form-codes',
    'substance-form-relationships',
    'substance-form-notes',
    'substance-form-properties',
    'substance-form-references',

  ],
  structurallyDiverse: [
    'substance-form-definition',
    'substance-form-names',
    'substance-form-structurally-diverse-source',
    'substance-form-structurally-diverse-organism',
    'substance-form-agent-modifications',
    'substance-form-structural-modifications',
    'substance-form-physical-modifications',
    'substance-form-codes',
    'substance-form-relationships',
    'substance-form-notes',
    'substance-form-properties',
    'substance-form-references',

  ],
  concept: [
    'substance-form-definition',
    'substance-form-names',
    'substance-form-codes',
    'substance-form-relationships',
    'substance-form-notes',
    'substance-form-properties',
    'substance-form-references',
  ],
  specifiedSubstanceG1: [
    'substance-form-definition',
    'substance-form-names',
    'substance-form-constituents',
    'substance-form-codes',
    'substance-form-relationships',
    'substance-form-notes',
    'substance-form-properties',
    'substance-form-references',
  ]
};
